version: '3'
services:
  mongodb-server:
    container_name: covid-19_mongodb
    image: 'mongo'
    ports:
      - '27017:27017'
  node-app:
    container_name: covid-19_nodeapp
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - '8080:8080'
    links:
      - mongodb-server